version: '3'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: blogdb
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: blog